name: CI Checks

on:
    pull_request:
        branches:
            - main

jobs:
    checks:
        runs-on: [self-hosted, ubuntu-latest]
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm run test
              