name: CI Checks

on:
    pull_request:
        branches:
            - main
        types:
            - opened
            - edited
            - reopened
            - synchronize

jobs:
    check_pr_type:
        runs-on: ubuntu-latest
        steps:
            - name: Check PR title
              id: get-pr-title
              run: echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT

            - name: Check PR type
              run: |
                if [[ ! $PR_TITLE =~ ^#(chore|feat) ]]; then
                    echo "PR title must contain #chore or #feat"
                    exit 1
                fi

    checks:
        runs-on: [self-hosted, ubuntu-latest]
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm run test
              