name: Release AST Inspector VSIX

on:
    push:
        branches:
            - main

jobs:
    check_push:
        outputs:
            is_feat_or_bug: ${{ steps.check_commit_type.outputs.is_feat_or_bug }}
            is_release: ${{ steps.check_commit_type.outputs.is_release }}
        runs-on: ubuntu-latest
        steps:
            - name: Check commit type
              id: check_commit_type
              run: |
                COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
                
                # Check if this is a release PR (format: "Release v1.2.3")
                if [[ "$COMMIT_MESSAGE" =~ ^Release\ v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
                    echo "Release commit detected, proceeding with VSIX release"
                    echo "is_release=true" >> $GITHUB_OUTPUT
                    echo "is_feat_or_bug=false" >> $GITHUB_OUTPUT
                elif [[ "$COMMIT_MESSAGE" =~ ^\#(feat|bug) ]]; then
                    echo "Feature or bug commit detected, proceeding with release preparation"
                    echo "is_feat_or_bug=true" >> $GITHUB_OUTPUT
                    echo "is_release=false" >> $GITHUB_OUTPUT
                else
                    echo "No release action needed for this commit"
                    echo "is_feat_or_bug=false" >> $GITHUB_OUTPUT
                    echo "is_release=false" >> $GITHUB_OUTPUT
                fi

    prepare_release:
        needs: check_push
        permissions:
            contents: write
            actions: read
            security-events: write
            issues: write
            pull-requests: write
        if: ${{ needs.check_push.outputs.is_feat_or_bug == 'true' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Check if release branch exists
              id: check_branch
              run: |
                git fetch origin
                if git show-ref --verify --quiet refs/remotes/origin/release-vsix; then
                  echo "Release branch exists, skipping version bump"
                  echo "should_bump=false" >> $GITHUB_OUTPUT
                else
                  echo "Release branch doesn't exist, will bump version"
                  echo "should_bump=true" >> $GITHUB_OUTPUT
                fi

            - name: Install dependencies
              run: |
                npm install
                cd frontend && npm install
                cd ..
            
            - name: Clear any package-lock changes
              run: git checkout -- .

            - name: Configure Git
              run: |
                git config --global user.email "luau-ast-explorer-bot@users.noreply.github.com"
                git config --global user.name "luau-ast-explorer-bot"

            - name: Bump Version
              if: ${{ steps.check_branch.outputs.should_bump == 'true' }}
              run: |
                npm version patch
            
            - name: Get version
              id: get-version
              run: |
                VERSION=$(cat package.json | jq -r '.version')
                echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

            - name: Process Changelog
              run: |
                echo "Processing changelog files for version ${{ steps.get-version.outputs.VERSION }}..."
                npm run process-changelog ${{ steps.get-version.outputs.VERSION }}

            - name: Create PR for Release
              uses: peter-evans/create-pull-request@v6
              with:
                title: 'Release v${{ steps.get-version.outputs.VERSION }}'
                body: |
                  🚀 **Release v${{ steps.get-version.outputs.VERSION }}**
                  
                  This PR contains:
                  - Version bump to ${{ steps.get-version.outputs.VERSION }}
                  - Updated CHANGELOG.md
                  
                  **To complete the release:**
                  1. Review the changes
                  2. Merge this PR to trigger the release

                branch: release-vsix
                base: main
                author: 'luau-ast-explorer-bot <luau-ast-explorer-bot@users.noreply.github.com>'
                token: ${{ secrets.AUTH_PAT }}
                delete-branch: true

    release_vsix:
        needs: check_push
        permissions:
            contents: write
        if: ${{ needs.check_push.outputs.is_release == 'true' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: |
                npm install
                cd frontend && npm install
                cd ..
            
            - name: Install VSCE
              run: npm install -g @vscode/vsce

            - name: Get version
              id: get-version
              run: |
                VERSION=$(cat package.json | jq -r '.version')
                echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

            - name: Build
              run: npm run compile

            - name: Package
              run: npm run package

            - name: Create release
              uses: softprops/action-gh-release@v2
              with:
                tag_name: v${{ steps.get-version.outputs.VERSION }}
                name: v${{ steps.get-version.outputs.VERSION }}
                files: ./luau-ast-explorer-${{ steps.get-version.outputs.VERSION }}.vsix
                draft: false
                prerelease: false
                token: ${{ secrets.GITHUB_TOKEN }}
                generate_release_notes: true
